# Generated by Django 5.2.4 on 2025-07-12 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
